server:
  port: 8080
  error:
    include-message: always

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: msvc-customer
          uri: lb://msvc-customer
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=1
        - id: msvc-product
          uri: lb://msvc-product
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1
        - id: msvc-shopping
          uri: lb://msvc-shopping
          predicates:
            - Path=/invoices/**
          filters:
            - StripPrefix=1