spring:
  application:
    name: msvc-customer
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      username: root
      password: pass4u
  boot:
    admin:
      client:
        url: http://localhost:9097
