spring:
  application:
    name: msvc-eureka
  cloud:
    config:
      uri: http://localhost:8888
      username: root
      password: pass4u
  config:
    import: optional:configserver:http://localhost:8888

