server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:GabrielLevanoR/store-microservices.git
          search-paths: config-data
  security:
    user: root
    password: pass4u
